- build.gradle
- settings.gradle
- src/main/java/com/example/demo/common/aop/A.java
- src/main/java/com/example/demo/common/jwt/J.java
- src/main/java/com/example/demo/common/util/U.java
- src/main/java/com/odiga/fiesta/DemoApplication.java
- src/main/java/com/odiga/fiesta/common/ApiResponse.java
- src/main/java/com/odiga/fiesta/common/aop/A.java
- src/main/java/com/odiga/fiesta/common/config/JpaAuditingConfig.java
- src/main/java/com/odiga/fiesta/common/domain/BaseEntity.java
- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/common/error/ErrorResponse.java
- src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
- src/main/java/com/odiga/fiesta/common/error/exception/CustomException.java
- src/main/java/com/odiga/fiesta/common/jwt/J.java
- src/main/java/com/odiga/fiesta/common/util/U.java
- src/main/java/com/odiga/fiesta/hello/controller/HelloController.java
- src/test/java/com/odiga/fiesta/ControllerTestSupport.java
- src/test/java/com/odiga/fiesta/DemoApplicationTests.java
- src/test/java/com/odiga/fiesta/hello/controller/HelloControllerTest.java
서비스 이름과 팀명이 정해졌으므로, 해당 이름으로 project name, artifacts, group 명 변경하였습니다.
close #7
> env: project name, artifacts, group 명 변경

- src/test/java/com/odiga/fiesta/ControllerTestSupport.java
- src/test/java/com/odiga/fiesta/IntegrationTestSupport.java
- src/test/java/com/odiga/fiesta/MockTestSupport.java
- src/test/java/com/odiga/fiesta/RepositoryTestSupport.java
일관된 환경에서 테스트를 관리하기 위해 `TestSupport` 클래스를 구현합니다.
특히 Slice Test 를 통해, 각 Bean 을 최소로 등록시키고 Spring boot 서버가 새로 실행되는 시간을 최소화 하고자 합니다.
- 주로 Service layer 에 사용하는 `IntergrationTest` 의 경우, 테스트 간 독립성을 편하게 보장하기 위해 `@Transactional` 애노테이션을 사용하였습니다.
그러나 이 경우, 실제 서비스 구현 시 해당 애노테이션이 누락되었을 때에 대해 예외를 찾을 수 없으므로 유의하여야 합니다.
- 노션의 가이드 문서를 새로 작성하였습니다. (https://breakyourlimit.notion.site/eb7d7d032a2f48578a58eb0bd8295995?pvs=4)
close #6
> feat: 테스트 환경 구성 

- build.gradle
- src/main/java/com/odiga/fiesta/common/config/SwaggerConfig.java
> feat: Swagger 설정

- .gitignore
- build.gradle
- src/main/java/com/odiga/fiesta/common/config/QueryDslConfig.java
> feat: QueryDsl 설정

- src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
- src/test/java/com/odiga/fiesta/hello/controller/HelloControllerTest.java
feat: ExceptionHandler 에서 404 에러 처리 추가
close #14
> feat: ExceptionHandler 에서 404 에러 처리 추가

- src/main/java/com/odiga/fiesta/common/filter/LogFilter.java
- src/test/java/com/odiga/fiesta/common/filter/LogFilterTest.java
http request 에 대한 logging 구현 
우선 http request 에 대한 간단한 부분만 로그를 출력하도록 구현했습니다.
request 객체 분석 같은 건, 어떤걸 로그로 출력할지 논의 후 구현해야 할 것 같아요.
close #5
> feat: http request 에 대한 logging 구현

- build.gradle
- src/main/java/com/odiga/fiesta/common/config/CorsMvcConfig.java
- src/main/java/com/odiga/fiesta/common/config/SecurityConfig.java
- src/test/java/com/odiga/fiesta/ControllerTestSupport.java
Spring Security 기본 설정 추가
JWT, OAuth2.0 관련 설정들은 유저 enitity 나온 후에 구현하는 걸로.. 우선 config 파일만 세팅해놓겠습니다.
close #17
> env: Security 기본 설정

- .github/workflows/pr-ci.yml
- build.gradle
- lombok.config
PR CI 구현
test coverage line 단위 70% 이상 통과하지 못하면 test 가 실패하도록 설정하였습니다.
ci 단계에서 pr 이 실패하면 이 원인일 가능성이 높습니다!
터미널에서 `./gredlew test` 로 확인해볼 수 있습니다. 
jacoco 보고서는
`build/reports/jacoco/test/html` 에서 확인할 수 있습니다.
테스트 코드를 짜기 애매한 `dto`, `common`, `~Application`은 커버리지 산출 대상에서 제외시켰으며 `repository` 역시 단순히 Spring Data JPA 에서 제공하는 쿼리메서드를 사용하는 경우 의미가 없다 생각하여 제외하였으나, **`querydsl`을 사용하거나 직접 짠 쿼리에 대해서는 테스트 케이스를 작성하는 것이 좋을 것 같습니다.** 
test가 실패하는 경우 pr이 실패하며 merge 할 수 없습니다.
각 test 결과는 bot의 comment 로 확인할 수 있습니다. 
> test가 실패하는 경우 : 테스트가 실패하는 경우, 테스트 커버리지를 만족하지 못한 경우
또한 테스트가 실패하는 경우 `mikepenz/action-junit-report@v4` 액션에 의해 어디에서 실패했는지 추적할 수 있습니다. 
close #19
> feat: pr ci 구현

- src/main/java/com/odiga/fiesta/common/ApiResponse.java
- src/main/java/com/odiga/fiesta/common/PageResponse.java
> feat: `PageResponse` 구현

- build.gradle
- src/main/java/com/odiga/fiesta/common/config/S3Config.java
- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/common/error/exception/s3/InvalidExtensionException.java
- src/main/java/com/odiga/fiesta/common/error/exception/s3/InvalidImageException.java
- src/main/java/com/odiga/fiesta/common/error/exception/s3/UploadFailException.java
- src/main/java/com/odiga/fiesta/s3/service/S3Service.java
- src/main/java/com/odiga/fiesta/user/domain/accounts/OauthUser.java
- src/main/java/com/odiga/fiesta/user/domain/oauth/OauthProvider.java
- src/main/java/com/odiga/fiesta/user/oauth/OauthProvider.java
- src/test/java/S3MockConfig.java
- src/test/java/com/odiga/fiesta/s3/service/S3ServiceTest.java
S3를 이용하여 이미지를 업로드하는 기능을 구현합니다. 
`dirName` 은 도메인 따라가면 됩니다.
예를 들어 `review` 도메인에서 이미지 업로드하실 때는 `review` 넣으시면 됩니다.
close #39
> feat: 이미지 업로드 기능 구현

- build.gradle
- src/main/java/com/odiga/fiesta/common/config/RedisConfig.java
- src/main/java/com/odiga/fiesta/common/util/RedisUtils.java
- src/main/java/com/odiga/fiesta/common/util/U.java
- src/main/resources/application-local.yml
- src/main/resources/application-test.yml
- src/test/java/EmbeddedRedisConfig.java
사용방법 : https://developer-nyong.tistory.com/21
- 로컬 실행시, redis 실행시켜놔야 정상적으로 실행됩니다! (테스트는 상관X)
close #43
> env: Redis 기본 설정

- src/main/java/com/odiga/fiesta/category/domain/Category.java
- src/main/java/com/odiga/fiesta/category/repository/CategoryRepository.java
- src/main/java/com/odiga/fiesta/companion/domain/Companion.java
- src/main/java/com/odiga/fiesta/companion/repository/CompanionRepository.java
- src/main/java/com/odiga/fiesta/festival/dto/response/CategoryResponse.java
- src/main/java/com/odiga/fiesta/festival/dto/response/CompanionResponse.java
- src/main/java/com/odiga/fiesta/festival/dto/response/MoodResponse.java
- src/main/java/com/odiga/fiesta/festival/dto/response/PriorityResponse.java
- src/main/java/com/odiga/fiesta/festival/service/CategoryService.java
- src/main/java/com/odiga/fiesta/festival/service/CompanionService.java
- src/main/java/com/odiga/fiesta/festival/service/MoodService.java
- src/main/java/com/odiga/fiesta/festival/service/PriorityService.java
- src/main/java/com/odiga/fiesta/mood/domain/Mood.java
- src/main/java/com/odiga/fiesta/mood/repository/MoodRepository.java
- src/main/java/com/odiga/fiesta/priority/domain/Priority.java
- src/main/java/com/odiga/fiesta/priority/repository/PriorityRepository.java
- src/test/java/com/odiga/fiesta/festival/service/CategoryServiceTest.java
- src/test/java/com/odiga/fiesta/festival/service/CompanionServiceTest.java
- src/test/java/com/odiga/fiesta/festival/service/MoodServiceTest.java
- src/test/java/com/odiga/fiesta/festival/service/PriorityServiceTest.java
> refactor: 정적 데이터 도메인 분리

- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/festival/domain/FestivalBookmark.java
- src/main/java/com/odiga/fiesta/festival/dto/request/FestivalFilterRequest.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalBookmarkResponse.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalBookmarkRepository.java
- src/main/java/com/odiga/fiesta/festival/service/FestivalBookmarkService.java
- src/test/java/com/odiga/fiesta/ControllerTestSupport.java
- src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalBookmarkServiceTest.java
페스티벌 북마크 등록/해제 구현
북마크는 유저의 북마크를 찾을 수 있다면 삭제, 없다면 생성하는 방식입니다.
close #45
> feat: 페스티벌 북마크 등록/해제 구현

- src/main/java/com/odiga/fiesta/sido/domain/Sido.java
- src/main/resources/db/migration/V8__change_table_name.sql
> hotfix: 테이블 이름 인식 못하는 오류 수정

- src/main/java/com/odiga/fiesta/log/service/LogService.java
- src/test/java/com/odiga/fiesta/log/service/LogMockServiceTest.java
UserRepository 위치를 변경으로 인해 build 에러가 뜨는 것 같아, 해당 부분 수정했습니다.
close #72
> refactor: UserRepository 위치 변경

- src/main/java/com/odiga/fiesta/festival/dto/projection/FestivalDetailData.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalDetailResponse.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
> feat: 페스티벌 상세 조회 응답에 위도,경도 추가

- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalAndLocation.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
- src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
- src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
다가오는 페스티벌 조회 API 를 구현합니다.
close #74
> feat: 다가오는 페스티벌 조회 API 구현

- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/festival/domain/FestivalUserType.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalUserTypeRepository.java
- src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
- src/main/java/com/odiga/fiesta/user/repository/UserRepository.java
- src/main/resources/db/migration/V12__create_festivalusertype.sql
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
> feat: 추천 페스티벌 조회 API 구현

- src/main/java/com/odiga/fiesta/auth/service/AuthService.java
- src/main/java/com/odiga/fiesta/user/controller/UserController.java
- src/main/java/com/odiga/fiesta/user/dto/response/UserInfoResponse.java
- src/main/java/com/odiga/fiesta/user/service/UserService.java
로그인한 유저의 정보를 조회하는 api 를 구현합니다.
close #91
> feat: 내 정보 조회 api 구현

- src/main/java/com/odiga/fiesta/auth/service/AuthService.java
- src/main/java/com/odiga/fiesta/user/controller/UserController.java
> feat: 회원 탈퇴 api 구현

- src/main/java/com/odiga/fiesta/user/domain/UserType.java
- src/main/java/com/odiga/fiesta/user/dto/request/UserRequest.java
- src/main/java/com/odiga/fiesta/user/dto/response/UserResponse.java
- src/main/java/com/odiga/fiesta/user/service/UserService.java
- src/main/resources/db/migration/V17__create_new_user_type.sql
figma 가 변하면서 삭제된 이미지 데이터를 수정하고,
데이터 구조를 변경한다.
close #103
> hotfix: 삭제된 이미지 데이터 수정

- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/common/error/GlobalExceptionHandler.java
- src/main/java/com/odiga/fiesta/festival/dto/request/FestivalCreateRequest.java
- src/main/resources/application.yml
> hotfix: max-request-size 수정

- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/review/dto/response/ReviewKeywordResponse.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
모든 리뷰 키워드 조회  api 를 구현한다.
close #117
> feat: 모든 리뷰 키워드 조회  api 구현

- build.gradle
- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/review/domain/Review.java
- src/main/java/com/odiga/fiesta/review/dto/request/ReviewCreateRequest.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
- src/test/java/com/odiga/fiesta/ControllerTestSupport.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
- src/test/java/com/odiga/fiesta/review/controller/ReviewControllerTest.java
- src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
> feat: 리뷰 생성 API 구현

- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/review/dto/response/ReviewLikeResponse.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewLikeRepository.java
- src/main/java/com/odiga/fiesta/review/service/ReviewLikeService.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
- src/test/java/com/odiga/fiesta/ControllerTestSupport.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalBookmarkServiceTest.java
- src/test/java/com/odiga/fiesta/review/service/ReviewLikeServiceTest.java
리뷰 좋아요 등록/해제 api를 구현합니다.
close #105
> feat: 리뷰 좋아요 등록/해제 구현

- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewImageRepository.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewLikeRepository.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
- src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
> feat: 리뷰 삭제 API 구현

- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/festival/domain/FestivalModificationRequest.java
- src/main/java/com/odiga/fiesta/festival/dto/request/CreateFestivalModificationRequest.java
- src/main/java/com/odiga/fiesta/festival/dto/request/FestivalModificationRequest.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalModificationResponse.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalModificationRequestRepository.java
- src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
- src/main/resources/db/migration/V22__add_festival_modification_request.sql
- src/test/java/com/odiga/fiesta/festival/controller/FestivalControllerTest.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
페스티벌 수정 사항 요청 api를 구현합니다.
- erd
close #144
> feat: 페스티벌 수정 사항 요청 api 구현

- src/main/java/com/odiga/fiesta/user/service/UserService.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
- src/test/java/com/odiga/fiesta/user/service/UserServiceTest.java
프로필 생성 시, 관련 정보를 응답하지 않는 에러를 수정합니다.
close #149
> fix: 프로필 생성 시, 관련 정보 응답하지 않는 문제 수정

- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalBasic.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalInfo.java
- src/main/java/com/odiga/fiesta/festival/dto/response/FestivalInfoWithBookmark.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepository.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalCustomRepositoryImpl.java
- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/user/controller/UserController.java
- src/main/java/com/odiga/fiesta/user/service/UserService.java
- src/test/java/com/odiga/fiesta/festival/repository/FestivalRepositoryTest.java
- src/test/java/com/odiga/fiesta/user/service/UserServiceTest.java
현재 유저가 북마크한 페스티벌 조회 API를 구현합니다.
close #151
> feat: 현재 유저가 북마크한 페스티벌 조회 API 구현

- src/main/java/com/odiga/fiesta/festival/controller/FestivalController.java
- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/review/domain/ReviewReport.java
- src/main/java/com/odiga/fiesta/review/dto/request/ReviewReportRequest.java
- src/main/java/com/odiga/fiesta/review/dto/response/ReviewReportResponse.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewReportRepository.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
- src/main/resources/db/migration/V23__add_review_report.sql
- src/test/java/com/odiga/fiesta/review/service/ReviewServiceTest.java
> feat: 리뷰 신고 api 구현 

- src/main/resources/db/migration/V24__drop_log_table.sql
삭제된 기능 (방문일지) 와 관련된 테이블을 삭제합니다.
close #148
> feat: 방문일지 관련 테이블 삭제

- src/main/java/com/odiga/fiesta/auth/service/AuthService.java
- src/main/java/com/odiga/fiesta/badge/domain/Badge.java
- src/main/java/com/odiga/fiesta/badge/domain/BadgeConstants.java
- src/main/java/com/odiga/fiesta/badge/domain/BadgeType.java
- src/main/java/com/odiga/fiesta/badge/domain/UserBadge.java
- src/main/java/com/odiga/fiesta/badge/repository/BadgeCustomRepository.java
- src/main/java/com/odiga/fiesta/badge/repository/BadgeCustomRepositoryImpl.java
- src/main/java/com/odiga/fiesta/badge/repository/BadgeRepository.java
- src/main/java/com/odiga/fiesta/badge/repository/UserBadgeRepository.java
- src/main/java/com/odiga/fiesta/badge/service/BadgeService.java
- src/main/java/com/odiga/fiesta/category/domain/CategoryConstants.java
- src/main/java/com/odiga/fiesta/festival/domain/Festival.java
- src/main/java/com/odiga/fiesta/festival/repository/FestivalRepository.java
- src/main/java/com/odiga/fiesta/festival/service/FestivalService.java
- src/main/java/com/odiga/fiesta/review/domain/Review.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepository.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewRepository.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
- src/main/java/com/odiga/fiesta/user/controller/UserController.java
- src/main/java/com/odiga/fiesta/user/dto/response/UserBadgeResponse.java
- src/main/java/com/odiga/fiesta/user/service/UserService.java
- src/main/resources/db/migration/V25__add_index_for_badge.sql
- src/main/resources/db/migration/V26__add_temp_badge_data.sql
- src/test/java/com/odiga/fiesta/IntegrationTestSupport.java
- src/test/java/com/odiga/fiesta/badge/service/BadgeServiceTest.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceMockTest.java
- src/test/java/com/odiga/fiesta/festival/service/FestivalServiceTest.java
- src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
- src/test/java/com/odiga/fiesta/review/service/ReviewServiceTest.java
활동 뱃지 관련 기능을 구현합니다.
close #132
> feat: 활동뱃지 관련 기능 구현

- src/main/java/com/odiga/fiesta/common/error/ErrorCode.java
- src/main/java/com/odiga/fiesta/user/controller/UserController.java
- src/main/java/com/odiga/fiesta/user/domain/User.java
- src/main/java/com/odiga/fiesta/user/dto/request/UserInfoUpdateRequest.java
- src/main/java/com/odiga/fiesta/user/dto/response/UserIdResponse.java
- src/main/java/com/odiga/fiesta/user/service/UserService.java
- src/test/java/com/odiga/fiesta/user/service/UserServiceTest.java
유저 정보를 수정하는 api를 구현합니다.
close #156
> feat: 유저 정보 수정 api 구현

- src/main/java/com/odiga/fiesta/review/controller/ReviewController.java
- src/main/java/com/odiga/fiesta/review/dto/response/ReviewResponse.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepository.java
- src/main/java/com/odiga/fiesta/review/repository/ReviewCustomRepositoryImpl.java
- src/main/java/com/odiga/fiesta/review/service/ReviewService.java
- src/test/java/com/odiga/fiesta/review/service/ReviewServiceMockTest.java
> feat: 리뷰 단건 조회 구현

- src/main/java/com/odiga/fiesta/user/service/UserTypeService.java
> fix: 프로필 생성 버그 수정

- src/main/java/com/odiga/fiesta/user/controller/UserController.java
> fix: 오타 수정

- src/main/java/com/odiga/fiesta/auth/service/AuthService.java
- src/main/java/com/odiga/fiesta/user/controller/UserController.java
- src/main/java/com/odiga/fiesta/user/dto/response/UserInfoResponse.java
- src/main/java/com/odiga/fiesta/user/service/UserService.java
내 정보 조회의 `isProfileCreated` 필드의 이름을 `isProfileRegistered`로 변경한다.
close #178
> refactor: 필드 이름 `isProfileRegistered`로 변경
